
#+LaTeX_HEADER: \usepackage{pdfpages}
#+latex_header: \usepackage[bottom]{footmisc} %% to keep entire footers on one page
#+LATEX_HEADER: \usepackage[]{graphicx}
#+LATEX_HEADER: \usepackage[]{minted} 
#+LATEX_HEADER: \usepackage[a4paper,margin=1in]{geometry} 
#+LATEx_HEADER: \usepackage{comment}
#+latex_header: \usepackage[linesnumbered,ruled,lined,shortend]{algorithm2e}
#+latex_header: \usepackage[space]{grffile}

#+OPTIONS: todo:nil
#+OPTIONS: H:4
#+OPTIONS: num:4

\pagebreak


\vspace{5cm}

\Large  

\noindent
\textbf{Acknowledgements}

\normalsize
\vspace{13mm}

\noindent
I would first like to thank my two magnificent champions, Rupert Hughes and Nikolay Robinzonov. They have both invested their own time, spending many a late evening with me discussing ideas and helping make the hardest of the decisions. I would also like to thank Michael Scherer for invaluable feedback and an eagle eye, helping bring everything together at the end. The help of all three would not have been possible without the blessing of DEVnet GmbH, to whom I express my gratitude for all the support they have provided.\\

\vspace{5mm}
\noindent
On the academic side, I would like to thank Professor Yarema Okhrin of the Chair for Statistics at the University of Augsburg. I greatly appreciated his feedback, ideas, and patience with me from day one.\\


\vspace{5mm}
\noindent
Lastly, I must thank my brother and two sisters - not least for their proof-reading, but for their lasting support; giving me the inspiration and courage to live abroad and fulfil a dream. I dedicate this work to our amazing and loving parents, /Mum and Dad/.


\pagebreak



