(TeX-add-style-hook
 "5_Empirical_Studies"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("inputenc" "utf8") ("fontenc" "T1") ("ulem" "normalem") ("footmisc" "bottom") ("geometry" "a4paper" "margin=1in") ("algorithm2e" "linesnumbered" "ruled" "lined" "shortend") ("grffile" "space")))
   (add-to-list 'LaTeX-verbatim-environments-local "minted")
   (add-to-list 'LaTeX-verbatim-environments-local "lstlisting")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "lstinline")
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art10"
    "inputenc"
    "fontenc"
    "fixltx2e"
    "graphicx"
    "longtable"
    "float"
    "wrapfig"
    "rotating"
    "ulem"
    "amsmath"
    "textcomp"
    "marvosym"
    "wasysym"
    "amssymb"
    "hyperref"
    "minted"
    "listingsutf8"
    "enumitem"
    "mathtools"
    "pdflscape"
    "afterpage"
    "capt-of"
    "footmisc"
    "geometry"
    "comment"
    "algorithm2e"
    "grffile")
   (LaTeX-add-labels
    "chapter-empirical-studies"
    "sec-1"
    "sec-1-1"
    "tab:fin-data"
    "data_prep"
    "sec-1-2"
    "data-trans"
    "sec-1-2-1"
    "rescaling-sent"
    "sec-1-2-1-1"
    "weighting-sentiment"
    "sec-1-2-1-2"
    "eqn-reweight"
    "imputation"
    "sec-1-2-2"
    "sec-1-2-3"
    "weekend-sent"
    "sec-1-2-3-1"
    "fig:wwp"
    "combined-sent"
    "sec-1-2-3-2"
    "dummy-vars"
    "sec-1-2-3-3"
    "subsets"
    "sec-1-2-4"
    "tab_subsets"
    "lagged-subsets"
    "sec-1-2-4-1"
    "pairwise-corr"
    "sec-1-2-5"
    "alg-corr-cutoff"
    "fig:corr-cutoff"
    "data-exploration"
    "sec-1-3"
    "macro-view"
    "sec-1-3-1"
    "fig:tweet-counts-facet"
    "micro-view"
    "sec-1-3-2"
    "fig:day-to-day"
    "main-modelling"
    "sec-1-4"
    "param-grid"
    "sec-1-4-1"
    "results-gauss"
    "sec-1-4-2"
    "fig:glm-pred-acc"
    "fig:glm-errors"
    "results-bin"
    "sec-1-4-3"
    "fig:bin-pred-acc"
    "tab:top-bin-results"
    "sec-1-4-4"
    "price-paths"
    "sec-1-4-5"
    "fig:price-paths"
    "sec-1-4-6"
    "fig:growing-frame"
    "stochastic-boosting"
    "sec-1-5"
    "sec-1-5-1"
    "tab:tuning-grid"
    "sec-1-5-2"
    "fig:stoch-pred-acc"))
 :latex)

