(TeX-add-style-hook
 "TO_DO_modelling"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("inputenc" "utf8") ("fontenc" "T1") ("ulem" "normalem")))
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "url")
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art10"
    "inputenc"
    "fontenc"
    "fixltx2e"
    "graphicx"
    "longtable"
    "float"
    "wrapfig"
    "rotating"
    "ulem"
    "amsmath"
    "textcomp"
    "marvosym"
    "wasysym"
    "amssymb"
    "hyperref")
   (LaTeX-add-labels
    "sec-1"
    "sec-1-1"
    "sec-1-2"
    "sec-1-2-1"
    "sec-1-2-2"
    "sec-1-2-3"
    "sec-1-2-4"
    "sec-1-2-5"
    "sec-1-2-6"
    "sec-1-2-6-1"
    "sec-1-2-6-2"
    "sec-1-2-6-3"
    "sec-1-2-6-4"
    "sec-1-2-6-5"
    "sec-1-3"
    "sec-1-4"
    "sec-1-5"
    "sec-1-6"
    "sec-1-6-1"
    "sec-1-6-2"
    "sec-1-6-3"
    "sec-2"
    "sec-2-1"
    "sec-2-2"
    "sec-2-3"
    "sec-2-3-1"
    "sec-2-4"
    "sec-3"
    "sec-3-1"
    "sec-3-2"
    "sec-4"
    "sec-4-1"
    "sec-4-2"
    "sec-4-3"
    "sec-4-4"
    "sec-4-4-1"
    "sec-4-4-1-1"
    "sec-4-4-1-2"
    "sec-4-4-1-3"
    "sec-4-4-1-4"
    "sec-4-4-1-5"
    "sec-4-4-1-5-1"
    "sec-4-4-1-5-2"
    "sec-4-4-1-5-3"
    "sec-5"
    "sec-5-1"
    "sec-6"
    "sec-6-1"
    "sec-6-2"
    "sec-6-2-1"
    "sec-6-2-2"
    "sec-6-2-3"
    "sec-6-2-4"
    "sec-6-2-4-1"
    "sec-6-2-4-2"
    "sec-7"
    "sec-7-1"
    "sec-7-2"
    "sec-7-3"
    "sec-8"
    "sec-8-1"
    "sec-8-2"
    "sec-8-2-1"
    "sec-8-2-2"
    "sec-8-3"
    "sec-8-4"
    "sec-8-4-1"
    "sec-8-4-2"
    "sec-9"
    "sec-9-1"
    "sec-9-2"
    "sec-9-3"
    "sec-9-4"
    "sec-9-5"
    "sec-9-6"
    "sec-9-7"
    "sec-9-8"
    "sec-9-9"
    "sec-9-9-1"
    "sec-9-9-2"
    "sec-10"
    "sec-10-1"
    "sec-10-2"
    "sec-10-3"
    "sec-10-4"
    "sec-11")))

